//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:34:34 by fhey
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	

	public class BaseBuilding1
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string BuildNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string BuildName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PropertyRights { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? BuiltUpArea { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Address { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Province { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string City { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string District { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string InDepartment { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TotalMatter { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Developer { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TransactionPrefix { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? EntryDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PreLicenseNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PropertyType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ConstructionCategory { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PropertyCompany { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? ManagermentFee { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RenovatedState { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string DesignUnits { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? HandoverDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string InBusinessCircle { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string AdvertDesign { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? OpeningTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? ParkingNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Builders { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? BuildingStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ParcelNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? GreeningRate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? VolumeRate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ContractNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? GrantDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? AgentPoint { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Features { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? Covers { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string UseLife { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SalesAddress { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SalesTel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? SalesCompletionDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? AveragePrice { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsRecommend { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string BuildingIntroduction { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string AreaIntroduction { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TrafficIntroduction { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string OtherNote { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsReceivables { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Longitude { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Dimensions { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int ResidentCount { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? ManagermentFeeLimit { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? VolumeRateLimit { get; set; }
		 
      
    }
}

