//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-BaseHousesRoom 
    /// </summary>
	public partial class BaseHousesRoom
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long? SeatSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long? UnitSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? FloorNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RoomNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RoomNoRules { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsSales { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RoomName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsCaseConfirm { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsFinanceConfirm { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsLock { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsPreLock { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsSold { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsHidden { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsVirtual { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long? HousesTypeSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? PreSellCount { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? PreThirdSellCount { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? HousesPrice { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? HousesArea { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PropertyType { get; set; }
		  
    }
}
