//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-BaseHousesSeat 
    /// </summary>
	public partial class BaseHousesSeat
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SeatNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SeatName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SeatInfo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SeatType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PropertyType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string BuildingStructure { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? ManagermentFee { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? UnitNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int FloorNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? DoorNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string HousesTypeName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? Sort { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		  
    }
}
