//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-BillBuilding 
    /// </summary>
	public partial class BillBuilding
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 楼盘编号
		/// </summary>		
		public long BuildingSysNo { get; set; }
		
		/// <summary>
		/// 票据编号
		/// </summary>		
		public long BillNo { get; set; }
		
		/// <summary>
		/// 金额
		/// </summary>		
		public decimal? Money { get; set; }
		
		/// <summary>
		/// 领取人No
		/// </summary>		
		public string ReceiveSysNo { get; set; }
		
		/// <summary>
		/// 领取人名称
		/// </summary>		
		public string ReceiveName { get; set; }
		
		/// <summary>
		/// 使用状态:0:未使用，1:已使用，2:已作废
		/// </summary>		
		public int UseStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? UseDate { get; set; }
		
		/// <summary>
		/// 是否回收:0:未回收，1:已回收
		/// </summary>		
		public bool IsRecovery { get; set; }
		
		/// <summary>
		/// 归还人No
		/// </summary>		
		public string ReturnUserSysNo { get; set; }
		
		/// <summary>
		/// 归还人名称
		/// </summary>		
		public string ReturnUserName { get; set; }
		
		/// <summary>
		/// 回收日期
		/// </summary>		
		public DateTime? RecoveryDate { get; set; }
		
		/// <summary>
		/// 回收人No
		/// </summary>		
		public string RecoverySysNo { get; set; }
		
		/// <summary>
		/// 回收人名称
		/// </summary>		
		public string RecoveryName { get; set; }
		
		/// <summary>
		/// 创建时间（领用时间）
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 创建人（领用人）
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 创建人名称(领用人名称)
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 修改人
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 修改人名称
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 是否删除
		/// </summary>		
		public bool IsDelete { get; set; }
		  
    }
}
