//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-Building 
    /// </summary>
	public partial class Building
    {
		
		/// <summary>
		/// 系统编号
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 楼盘/案场编号
		/// </summary>		
		public string BuildNo { get; set; }
		
		/// <summary>
		/// 楼盘/案场名称
		/// </summary>		
		public string BuildName { get; set; }
		
		/// <summary>
		/// 楼盘/案场 产权名称
		/// </summary>		
		public string PropertyRights { get; set; }
		
		/// <summary>
		/// 建筑面积
		/// </summary>		
		public decimal? BuiltUpArea { get; set; }
		
		/// <summary>
		/// 家庭住址
		/// </summary>		
		public string Address { get; set; }
		
		/// <summary>
		/// 省/市
		/// </summary>		
		public string Province { get; set; }
		
		/// <summary>
		/// 城市
		/// </summary>		
		public string City { get; set; }
		
		/// <summary>
		/// 片区
		/// </summary>		
		public string District { get; set; }
		
		/// <summary>
		/// 所属事业部
		/// </summary>		
		public string InDepartment { get; set; }
		
		/// <summary>
		/// 事总
		/// </summary>		
		public string TotalMatter { get; set; }
		
		/// <summary>
		/// 开发商
		/// </summary>		
		public string Developer { get; set; }
		
		/// <summary>
		/// 成交单前缀
		/// </summary>		
		public string TransactionPrefix { get; set; }
		
		/// <summary>
		/// 进场日期
		/// </summary>		
		public DateTime? EntryDate { get; set; }
		
		/// <summary>
		/// 预售许可证号
		/// </summary>		
		public string PreLicenseNo { get; set; }
		
		/// <summary>
		/// 物业类型
		/// </summary>		
		public string PropertyType { get; set; }
		
		/// <summary>
		/// 建筑类别
		/// </summary>		
		public string ConstructionCategory { get; set; }
		
		/// <summary>
		/// 物业管理公司
		/// </summary>		
		public string PropertyCompany { get; set; }
		
		/// <summary>
		/// 物业管理费用
		/// </summary>		
		public decimal? ManagermentFee { get; set; }
		
		/// <summary>
		/// 装修状态
		/// </summary>		
		public string RenovatedState { get; set; }
		
		/// <summary>
		/// 设计单位
		/// </summary>		
		public string DesignUnits { get; set; }
		
		/// <summary>
		/// 交楼日期
		/// </summary>		
		public DateTime? HandoverDate { get; set; }
		
		/// <summary>
		/// 所属商圈
		/// </summary>		
		public string InBusinessCircle { get; set; }
		
		/// <summary>
		/// 广告设计
		/// </summary>		
		public string AdvertDesign { get; set; }
		
		/// <summary>
		/// 开盘时间
		/// </summary>		
		public DateTime? OpeningTime { get; set; }
		
		/// <summary>
		/// 停车位
		/// </summary>		
		public int? ParkingNum { get; set; }
		
		/// <summary>
		/// 建筑商
		/// </summary>		
		public string Builders { get; set; }
		
		/// <summary>
		/// 楼盘状态(准备:0/在售:1/撤销:2)
		/// </summary>		
		public int? BuildingStatus { get; set; }
		
		/// <summary>
		/// 宗地号
		/// </summary>		
		public string ParcelNo { get; set; }
		
		/// <summary>
		/// 绿化率
		/// </summary>		
		public decimal? GreeningRate { get; set; }
		
		/// <summary>
		/// 容积率
		/// </summary>		
		public decimal? VolumeRate { get; set; }
		
		/// <summary>
		/// 合同文号
		/// </summary>		
		public string ContractNo { get; set; }
		
		/// <summary>
		/// 批地日期
		/// </summary>		
		public DateTime? GrantDate { get; set; }
		
		/// <summary>
		/// 代理点数
		/// </summary>		
		public decimal? AgentPoint { get; set; }
		
		/// <summary>
		/// 项目特色
		/// </summary>		
		public string Features { get; set; }
		
		/// <summary>
		/// 占地面积
		/// </summary>		
		public decimal? Covers { get; set; }
		
		/// <summary>
		/// 使用年限
		/// </summary>		
		public string UseLife { get; set; }
		
		/// <summary>
		/// 售楼地址
		/// </summary>		
		public string SalesAddress { get; set; }
		
		/// <summary>
		/// 销售电话
		/// </summary>		
		public string SalesTel { get; set; }
		
		/// <summary>
		/// 销售完成日期
		/// </summary>		
		public DateTime? SalesCompletionDate { get; set; }
		
		/// <summary>
		/// 均价
		/// </summary>		
		public decimal? AveragePrice { get; set; }
		
		/// <summary>
		/// 是否推荐
		/// </summary>		
		public bool? IsRecommend { get; set; }
		
		/// <summary>
		/// 楼盘/案场 介绍
		/// </summary>		
		public string BuildingIntroduction { get; set; }
		
		/// <summary>
		/// 区域介绍
		/// </summary>		
		public string AreaIntroduction { get; set; }
		
		/// <summary>
		/// 区域交通
		/// </summary>		
		public string TrafficIntroduction { get; set; }
		
		/// <summary>
		/// 其它备注
		/// </summary>		
		public string OtherNote { get; set; }
		
		/// <summary>
		/// 是否收款
		/// </summary>		
		public bool? IsReceivables { get; set; }
		
		/// <summary>
		/// 经度
		/// </summary>		
		public string Longitude { get; set; }
		
		/// <summary>
		/// 维度
		/// </summary>		
		public string Dimensions { get; set; }
		
		/// <summary>
		/// 驻场人数
		/// </summary>		
		public int ResidentCount { get; set; }
		
		/// <summary>
		/// 创建时间
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TotalMatterNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string InDepartmentName { get; set; }
		  
    }
}
