//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-Contract 
    /// </summary>
	public partial class Contract
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 合同文号
		/// </summary>		
		public string ContractNo { get; set; }
		
		/// <summary>
		/// 单位名称
		/// </summary>		
		public string UnitName { get; set; }
		
		/// <summary>
		/// 合同类型
		/// </summary>		
		public int ContracType { get; set; }
		
		/// <summary>
		/// 开户名称
		/// </summary>		
		public string AccName { get; set; }
		
		/// <summary>
		/// 开户行
		/// </summary>		
		public string AccBank { get; set; }
		
		/// <summary>
		/// 开户账号
		/// </summary>		
		public string AccBankNo { get; set; }
		
		/// <summary>
		/// 审批状态
		/// </summary>		
		public int ApprovalStatus { get; set; }
		
		/// <summary>
		/// 开始时间
		/// </summary>		
		public DateTime? StarTime { get; set; }
		
		/// <summary>
		/// 结束时间
		/// </summary>		
		public DateTime? EndTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? DevFeeRate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? ParFeeRate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		  
    }
}
