//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-CustomerDemand 
    /// </summary>
	public partial class CustomerDemand
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 客户编号
		/// </summary>		
		public long? CustomerSysNo { get; set; }
		
		/// <summary>
		/// 需求房型
		/// </summary>		
		public string DemandRoomType { get; set; }
		
		/// <summary>
		/// 需求单价
		/// </summary>		
		public decimal? DemandPrice { get; set; }
		
		/// <summary>
		/// 需求总价
		/// </summary>		
		public decimal? DemandTotalPrice { get; set; }
		
		/// <summary>
		/// 需求面积
		/// </summary>		
		public decimal? DemandArea { get; set; }
		
		/// <summary>
		/// 房龄
		/// </summary>		
		public int? HousesAge { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		  
    }
}
