//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-CustomerRemark 
    /// </summary>
	public partial class CustomerRemark
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long CustomerSysNo { get; set; }
		
		/// <summary>
		/// 级别(A:1;B:2;C:3;D:4;)
		/// </summary>		
		public int? Level { get; set; }
		
		/// <summary>
		/// 客户状态
		/// </summary>		
		public int? CustomerStatus { get; set; }
		
		/// <summary>
		/// 拜访时间
		/// </summary>		
		public DateTime? VisitTime { get; set; }
		
		/// <summary>
		/// 陪同类型
		/// </summary>		
		public int? AccompaniedType { get; set; }
		
		/// <summary>
		/// 陪同人信息
		/// </summary>		
		public string AccompaniedInformation { get; set; }
		
		/// <summary>
		/// 需求房型
		/// </summary>		
		public string DemandRoomType { get; set; }
		
		/// <summary>
		/// 需求单价
		/// </summary>		
		public decimal? DemandPrice { get; set; }
		
		/// <summary>
		/// 需求总价
		/// </summary>		
		public decimal? DemandTotalPrice { get; set; }
		
		/// <summary>
		/// 需求面积
		/// </summary>		
		public decimal? DemandArea { get; set; }
		
		/// <summary>
		/// 需求房龄
		/// </summary>		
		public int? HousesAge { get; set; }
		
		/// <summary>
		/// 删除标记
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remark { get; set; }
		
		/// <summary>
		/// 面积
		/// </summary>		
		public decimal? AreaSum { get; set; }
		
		/// <summary>
		/// 客厅
		/// </summary>		
		public int? HallSum { get; set; }
		
		/// <summary>
		/// 房间
		/// </summary>		
		public int? RoomSum { get; set; }
		
		/// <summary>
		/// 卫生间
		/// </summary>		
		public int? ToiletSum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CustomerTag { get; set; }
		  
    }
}
