//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-Duty 
    /// </summary>
	public partial class Duty
    {
		
		/// <summary>
		/// 部门主键
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 部门编号
		/// </summary>		
		public string DutyNo { get; set; }
		
		/// <summary>
		/// 部门名称
		/// </summary>		
		public string DutyName { get; set; }
		
		/// <summary>
		/// 创建人
		/// </summary>		
		public long CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 创建时间
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 修改人
		/// </summary>		
		public long? ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		  
    }
}
