//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-Employees 
    /// </summary>
	public partial class Employees
    {
		
		/// <summary>
		/// 系统主键
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 员工工号
		/// </summary>		
		public string EmpNo { get; set; }
		
		/// <summary>
		/// 员工姓名
		/// </summary>		
		public string EmpName { get; set; }
		
		/// <summary>
		/// 员工手机号
		/// </summary>		
		public string Mobile { get; set; }
		
		/// <summary>
		/// 员工域帐户
		/// </summary>		
		public string EmailAddr { get; set; }
		
		/// <summary>
		/// 部门名称
		/// </summary>		
		public string Department { get; set; }
		
		/// <summary>
		/// 职位
		/// </summary>		
		public string Duty { get; set; }
		
		/// <summary>
		/// 状态(0:驻场;1:非驻场)
		/// </summary>		
		public bool IsResidentStatus { get; set; }
		
		/// <summary>
		/// 上级编号
		/// </summary>		
		public long SuperiorNo { get; set; }
		
		/// <summary>
		/// 创建者
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 创建时间
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 修改者
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 是否标记删除
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 是否可以登录
		/// </summary>		
		public bool IsSwitch { get; set; }
		
		/// <summary>
		/// 域名
		/// </summary>		
		public string DomainName { get; set; }
		
		/// <summary>
		/// 最后登录时间
		/// </summary>		
		public DateTime? LastLoginTime { get; set; }
		
		/// <summary>
		/// 锁定时间
		/// </summary>		
		public DateTime? LockTime { get; set; }
		
		/// <summary>
		/// 连续登陆错误次数 暂时方案
		/// </summary>		
		public int ErrorCount { get; set; }
		
		/// <summary>
		/// 系统锁定
		/// </summary>		
		public bool SystemLock { get; set; }
		
		/// <summary>
		/// 是否离职(0:在职;1:离职;)
		/// </summary>		
		public bool IsResignation { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ReleaseLockTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long? ReleaseLockOperator { get; set; }
		  
    }
}
