//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-Filing 
    /// </summary>
	public partial class Filing
    {
		
		/// <summary>
		/// 系统标记
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 报备编号
		/// </summary>		
		public string FilingNo { get; set; }
		
		/// <summary>
		/// 客户编号
		/// </summary>		
		public long InCustomerSysNo { get; set; }
		
		/// <summary>
		/// 自然人
		/// </summary>		
		public long? InPersonSysNo { get; set; }
		
		/// <summary>
		/// 楼盘编号
		/// </summary>		
		public long InBuildingSysNo { get; set; }
		
		/// <summary>
		/// 报备类型(1:外场;2:来电;3:来访;)
		/// </summary>		
		public int FilingType { get; set; }
		
		/// <summary>
		/// 报备状态(0:有效;1:;无效)
		/// </summary>		
		public bool FilingStatus { get; set; }
		
		/// <summary>
		/// 绑定(0:否;1:是)
		/// </summary>		
		public bool Binding { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string InEmployeesSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string InDepartmentNo { get; set; }
		  
    }
}
