//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-HousesUnit 
    /// </summary>
	public partial class HousesUnit
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 单元编号
		/// </summary>		
		public string UnitNo { get; set; }
		
		/// <summary>
		/// 单元名称
		/// </summary>		
		public string UnitName { get; set; }
		
		/// <summary>
		/// 单元房间数
		/// </summary>		
		public int? UnitDoorNum { get; set; }
		
		/// <summary>
		/// 单元楼层数
		/// </summary>		
		public int? UnitFloorNum { get; set; }
		
		/// <summary>
		/// 是否虚拟单元(默认是实体单元)
		/// </summary>		
		public bool IsVirtual { get; set; }
		
		/// <summary>
		/// 创建时间
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		  
    }
}
