//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-HousesSeat 
    /// </summary>
	public partial class HousesSeat
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 栋座编号
		/// </summary>		
		public string SeatNo { get; set; }
		
		/// <summary>
		/// 栋座名称
		/// </summary>		
		public string SeatName { get; set; }
		
		/// <summary>
		/// 栋座[信息]
		/// </summary>		
		public string SeatInfo { get; set; }
		
		/// <summary>
		/// 栋座类型
		/// </summary>		
		public string SeatType { get; set; }
		
		/// <summary>
		/// 物业类型
		/// </summary>		
		public string PropertyType { get; set; }
		
		/// <summary>
		/// 建筑结构
		/// </summary>		
		public string BuildingStructure { get; set; }
		
		/// <summary>
		/// 管理费
		/// </summary>		
		public decimal? ManagermentFee { get; set; }
		
		/// <summary>
		/// 单元数
		/// </summary>		
		public int? UnitNum { get; set; }
		
		/// <summary>
		/// 总层数
		/// </summary>		
		public int FloorNum { get; set; }
		
		/// <summary>
		/// 总户数
		/// </summary>		
		public int? DoorNum { get; set; }
		
		/// <summary>
		/// 栋座拥有的户型
		/// </summary>		
		public string HousesTypeName { get; set; }
		
		/// <summary>
		/// 创建时间
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? Sort { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		  
    }
}
