//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-HousesType 
    /// </summary>
	public partial class HousesType
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 对应楼盘
		/// </summary>		
		public long BuildingSysNo { get; set; }
		
		/// <summary>
		/// 户型编号
		/// </summary>		
		public string HousesTypeNo { get; set; }
		
		/// <summary>
		/// 户型名称
		/// </summary>		
		public string HousesTypeName { get; set; }
		
		/// <summary>
		/// 房间数量
		/// </summary>		
		public int RoomNum { get; set; }
		
		/// <summary>
		/// 厅数量
		/// </summary>		
		public int HallNum { get; set; }
		
		/// <summary>
		/// 卫生间数量
		/// </summary>		
		public int ToiletNum { get; set; }
		
		/// <summary>
		/// 阳台数量
		/// </summary>		
		public int? BalconyNum { get; set; }
		
		/// <summary>
		/// 花园数量
		/// </summary>		
		public int? GardenNum { get; set; }
		
		/// <summary>
		/// 建筑面积
		/// </summary>		
		public decimal? BuiltUpArea { get; set; }
		
		/// <summary>
		/// 使用面积
		/// </summary>		
		public decimal? UseArea { get; set; }
		
		/// <summary>
		/// 公摊面积
		/// </summary>		
		public decimal? ShareArea { get; set; }
		
		/// <summary>
		/// 指导价格
		/// </summary>		
		public decimal? GuidingPrice { get; set; }
		
		/// <summary>
		/// 户型朝向
		/// </summary>		
		public string Orientation { get; set; }
		
		/// <summary>
		/// 户型图
		/// </summary>		
		public string Picture { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		  
    }
}
