//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-IdentificationChips 
    /// </summary>
	public partial class IdentificationChips
    {
		
		/// <summary>
		/// 系统编号
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 认筹单业务编号
		/// </summary>		
		public string IdentificationChipsNo { get; set; }
		
		/// <summary>
		/// 自然人编号
		/// </summary>		
		public long PersonNo { get; set; }
		
		/// <summary>
		/// 所属案场编号
		/// </summary>		
		public long BuildingSysNo { get; set; }
		
		/// <summary>
		/// 销售顾问系统编号
		/// </summary>		
		public long EmployeeSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime IdentificationChipsDate { get; set; }
		
		/// <summary>
		/// 认筹金额
		/// </summary>		
		public decimal IdentificationChipsMoney { get; set; }
		
		/// <summary>
		/// 是否已经使用
		/// </summary>		
		public bool IsUsed { get; set; }
		
		/// <summary>
		/// 附件列表
		/// </summary>		
		public string FileListStr { get; set; }
		
		/// <summary>
		/// 创建人编号
		/// </summary>		
		public long CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 创建人姓名
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 创建时间
		/// </summary>		
		public DateTime? CreateDate { get; set; }
		
		/// <summary>
		/// 修改人系统编号
		/// </summary>		
		public long? ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 修改人姓名
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 是否删除
		/// </summary>		
		public bool IsDelete { get; set; }
		  
    }
}
