//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-OperatingRulesOrder 
    /// </summary>
	public partial class OperatingRulesOrder
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 楼盘编号
		/// </summary>		
		public long InBuildingNo { get; set; }
		
		/// <summary>
		/// 报备类型
		/// </summary>		
		public int FilingType { get; set; }
		
		/// <summary>
		/// 保护期类型
		/// </summary>		
		public int ProtectionType { get; set; }
		
		/// <summary>
		/// 规则顺序
		/// </summary>		
		public int RulesOrder { get; set; }
		
		/// <summary>
		/// 重复标记
		/// </summary>		
		public bool IsRepeat { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		  
    }
}
