//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-OrderParent 
    /// </summary>
	public partial class OrderParent
    {
		
		/// <summary>
		/// 订单编号
		/// </summary>		
		public long OrderParentNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long BuildingSysNo { get; set; }
		
		/// <summary>
		/// 案件编号
		/// </summary>		
		public long FillingProcessSysNo { get; set; }
		
		/// <summary>
		/// 客户编号
		/// </summary>		
		public long CustomerSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal OrderMoney { get; set; }
		
		/// <summary>
		/// 剩余拆分金额
		/// </summary>		
		public decimal SurplusSplitMoney { get; set; }
		
		/// <summary>
		/// 支付金额
		/// </summary>		
		public decimal PayMoney { get; set; }
		
		/// <summary>
		/// 创建时间（入库时间）
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 创建人
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 修改人
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 是否删除
		/// </summary>		
		public bool IsDelete { get; set; }
		  
    }
}
