//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-OrderPayInfo 
    /// </summary>
	public partial class OrderPayInfo
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 订单编号
		/// </summary>		
		public long OrderNo { get; set; }
		
		/// <summary>
		/// 银行账户
		/// </summary>		
		public string BankCardNo { get; set; }
		
		/// <summary>
		/// 是否建行卡
		/// </summary>		
		public bool IsCCB { get; set; }
		
		/// <summary>
		/// 发卡方编码
		/// </summary>		
		public string CardCode { get; set; }
		
		/// <summary>
		/// 支付方式:01：银行卡，02：现金
		/// </summary>		
		public string PayWay { get; set; }
		
		/// <summary>
		/// 交易类型:01：消费
		/// </summary>		
		public string TransactionType { get; set; }
		
		/// <summary>
		/// 通知类型：1：普通通知，2：应急通知
		/// </summary>		
		public string NetType { get; set; }
		
		/// <summary>
		/// POS机流水号
		/// </summary>		
		public string POSSerialNo { get; set; }
		
		/// <summary>
		/// POS批次号
		/// </summary>		
		public string POSBatchNo { get; set; }
		
		/// <summary>
		/// 银联参考号
		/// </summary>		
		public string HostSerial { get; set; }
		
		/// <summary>
		/// 银联授权号
		/// </summary>		
		public string AuthCode { get; set; }
		
		/// <summary>
		/// 商户号
		/// </summary>		
		public string MerchantNo { get; set; }
		
		/// <summary>
		/// POS终端号
		/// </summary>		
		public string POSTNo { get; set; }
		
		/// <summary>
		/// POS系统流水号
		/// </summary>		
		public string POSSystemSerial { get; set; }
		
		/// <summary>
		/// 交易时间
		/// </summary>		
		public DateTime TransactionTime { get; set; }
		
		/// <summary>
		/// 支付金额
		/// </summary>		
		public decimal PayMoney { get; set; }
		
		/// <summary>
		/// 效验信息
		/// </summary>		
		public string CheckValue { get; set; }
		
		/// <summary>
		/// 创建时间（入库时间）
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 创建人
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 创建人名称
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 修改人
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 修改人名称
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 是否删除
		/// </summary>		
		public bool IsDelete { get; set; }
		  
    }
}
