//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-Order 
    /// </summary>
	public partial class Order
    {
		
		/// <summary>
		/// 订单编号
		/// </summary>		
		public long OrderNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal OrderMoney { get; set; }
		
		/// <summary>
		/// 订单状态:0:待支付，1:已支付，-1：支付失败，2：应急支付
		/// </summary>		
		public int PayStatus { get; set; }
		
		/// <summary>
		/// 到款状态:0:未到账，1:已到账
		/// </summary>		
		public int ReceivingStatus { get; set; }
		
		/// <summary>
		/// 票据编号
		/// </summary>		
		public long? BillNo { get; set; }
		
		/// <summary>
		/// 是否是拆分订单:0:不是，1：是
		/// </summary>		
		public bool IsSplit { get; set; }
		
		/// <summary>
		/// 主订单号
		/// </summary>		
		public long? OrderParentNo { get; set; }
		
		/// <summary>
		/// 是否取消:0:未取消，1:已取消
		/// </summary>		
		public bool IsCancel { get; set; }
		
		/// <summary>
		/// 付款人名
		/// </summary>		
		public string PayerName { get; set; }
		
		/// <summary>
		/// 开户行名称
		/// </summary>		
		public string BankName { get; set; }
		
		/// <summary>
		/// 创建时间（入库时间）
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 创建人
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 修改人
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 是否删除
		/// </summary>		
		public bool IsDelete { get; set; }
		  
    }
}
