//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-PictureOtherData 
    /// </summary>
	public partial class PictureOtherData
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Affiliation { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remark { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsDeleted { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsNewObject { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string OperationSysNo { get; set; }
		  
    }
}
