//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-ProjectWashTempbak 
    /// </summary>
	public partial class ProjectWashTempbak
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int ID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Y_No { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Y_Name { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PTM_No { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PTM_Name { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PTM_Address { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PTM_Person { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PTM_Org { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PTM_Dept { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string After_No { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string After_Name { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string After_Address { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string After_Person { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string After_Dept { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string After_status { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string After_Sysno { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string exp1 { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string exp2 { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string exp3 { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? IsRepeat { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? IsPTMRepeat { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? IsWash { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? Batch { get; set; }
		  
    }
}
