//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-ProjectBuildRelationShip 
    /// </summary>
	public partial class ProjectBuildRelationShip
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long? Key { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long? ParentKey { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Name { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ParentName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? IsDel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Type { get; set; }
		  
    }
}
