//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-QuestionTemplate 
    /// </summary>
	public partial class QuestionTemplate
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TemplateName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? TemplateVersion { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? TemplateType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string QuestionStringList { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string QuestionMd5 { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsEnable { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long? BuildingSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		  
    }
}
