//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-Receivables 
    /// </summary>
	public partial class Receivables
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 收款规则编号
		/// </summary>		
		public string ReceivablesNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long BuildingNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int ReceivablesType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal ReceivablesMoney { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ReceivablesInfo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int ApprovalStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ReceivablesFile { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		  
    }
}
