//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-Refund 
    /// </summary>
	public partial class Refund
    {
		
		/// <summary>
		/// 退款编号
		/// </summary>		
		public long RefundNo { get; set; }
		
		/// <summary>
		/// 退款父编号
		/// </summary>		
		public long RefundParentNo { get; set; }
		
		/// <summary>
		/// 订单编号
		/// </summary>		
		public long OrderNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Money { get; set; }
		
		/// <summary>
		/// 退款状态:0:待退款，1:退款成功，-1:退款失败，2:人工退款成功，3:退款驳回
		/// </summary>		
		public int RefundStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? RefundTime { get; set; }
		
		/// <summary>
		/// 审核状态:0：待审核，1：审核通过，-1：审核驳回
		/// </summary>		
		public int ReviewStatus { get; set; }
		
		/// <summary>
		/// 批次号
		/// </summary>		
		public string BatchNo { get; set; }
		
		/// <summary>
		/// 创建时间
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 创建人
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 修改人
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 修改人名称
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 是否删除
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? BatchDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int ReviewLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsReapply { get; set; }
		  
    }
}
