//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-RelationEntity 
    /// </summary>
	public partial class RelationEntity
    {
		
		/// <summary>
		/// 主系统编号
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 父级节点编号
		/// </summary>		
		public long? RelationParentSysNo { get; set; }
		
		/// <summary>
		/// 实体类型
		/// </summary>		
		public int EntityType { get; set; }
		
		/// <summary>
		/// 指定节点可见
		/// </summary>		
		public long? RelationSonSysNo { get; set; }
		
		/// <summary>
		/// 关系可见深度
		/// </summary>		
		public int? RelationDepth { get; set; }
		
		/// <summary>
		/// 自定义属性1
		/// </summary>		
		public string Attribute1 { get; set; }
		
		/// <summary>
		/// 自定义属性2
		/// </summary>		
		public string Attribute2 { get; set; }
		
		/// <summary>
		/// 自定义属性3
		/// </summary>		
		public string Attribute3 { get; set; }
		
		/// <summary>
		/// 自定义属性4
		/// </summary>		
		public string Attribute4 { get; set; }
		
		/// <summary>
		/// 自定义属性5
		/// </summary>		
		public string Attribute5 { get; set; }
		
		/// <summary>
		/// 变动类型(创建/超时释放/上级划分等)
		/// </summary>		
		public int VestingSource { get; set; }
		
		/// <summary>
		/// 变动备注
		/// </summary>		
		public string VestingNote { get; set; }
		
		/// <summary>
		/// 创建者
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 创建日期
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 修改人
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 修改日期
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 逻辑删除标记
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Path { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string EntityId { get; set; }
		  
    }
}
