//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-Sequences 
    /// </summary>
	public partial class Sequences
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long ID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SeqName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long? SeqID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public long? Times { get; set; }
		  
    }
}
