//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-TransferAccountInfo 
    /// </summary>
	public partial class TransferAccountInfo
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 退款/转佣No
		/// </summary>		
		public long RelationNo { get; set; }
		
		/// <summary>
		/// 类型:2：退款，3：转佣
		/// </summary>		
		public int? Type { get; set; }
		
		/// <summary>
		/// 凭证号
		/// </summary>		
		public string CreditNo { get; set; }
		
		/// <summary>
		/// 处理方式
		/// </summary>		
		public string DealType { get; set; }
		
		/// <summary>
		/// 验证码
		/// </summary>		
		public string ValidateCode { get; set; }
		
		/// <summary>
		/// 输出内容1
		/// </summary>		
		public string Individual1 { get; set; }
		
		/// <summary>
		/// 输出内容名称2
		/// </summary>		
		public string IndividualName2 { get; set; }
		
		/// <summary>
		/// 输出内容2
		/// </summary>		
		public string Individual2 { get; set; }
		
		/// <summary>
		/// 备注1
		/// </summary>		
		public string Remark1 { get; set; }
		
		/// <summary>
		/// 备注2
		/// </summary>		
		public string Remark2 { get; set; }
		
		/// <summary>
		/// 创建时间（入库时间）
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 创建人
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 创建人名称
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 是否删除
		/// </summary>		
		public bool IsDelete { get; set; }
		  
    }
}
