//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-UserSecurity 
    /// </summary>
	public partial class UserSecurity
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StaffNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int ErrorCount { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsAuthorization { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool SystemLock { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? LockTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ReleaseLockTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ReleaseLockOperator { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? LastLoginTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string LoginIP { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remark { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Authorizer { get; set; }
		  
    }
}
