//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-UserOuter 
    /// </summary>
	public partial class UserOuter
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int SysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string UserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Password { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string BusinessPower { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string OperationPower { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RealName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string BusinessRule { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Company { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Department { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Address { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Duty { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Mobile { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Email { get; set; }
		  
    }
}
