//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-08-03 13:50:23 by jie
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	
    /// <summary>
    /// 实体-Vesting 
    /// </summary>
	public partial class Vesting
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long SysNo { get; set; }
		
		/// <summary>
		/// 客户编号
		/// </summary>		
		public long CustomerSysNo { get; set; }
		
		/// <summary>
		/// 归属类型(0：置业顾问；1：由公客到职业顾问；2：案场；3：事业部公客；4：公司；)
		/// </summary>		
		public int? VestingType { get; set; }
		
		/// <summary>
		/// 归属来源(1:自主创建；2：来访创建;3：超时释放；4：上级划分；5：自主挑选；6：自主释放；)
		/// </summary>		
		public int? VestingSource { get; set; }
		
		/// <summary>
		/// 来源备注
		/// </summary>		
		public string SourceRemarks { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModifyUserSysNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string InEmployeesSysNo { get; set; }
		  
    }
}
