//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuildingDto", Namespace="http://schemas.datacontract.org/2004/07/JMS.DTO.Ptm")]
    [System.SerializableAttribute()]
    public partial class BuildingDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BuildIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeveloperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.BuildingDto.HousesType[] HousesTypeDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildAddress {
            get {
                return this.BuildAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildAddressField, value) != true)) {
                    this.BuildAddressField = value;
                    this.RaisePropertyChanged("BuildAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BuildID {
            get {
                return this.BuildIDField;
            }
            set {
                if ((this.BuildIDField.Equals(value) != true)) {
                    this.BuildIDField = value;
                    this.RaisePropertyChanged("BuildID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildName {
            get {
                return this.BuildNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildNameField, value) != true)) {
                    this.BuildNameField = value;
                    this.RaisePropertyChanged("BuildName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildNo {
            get {
                return this.BuildNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildNoField, value) != true)) {
                    this.BuildNoField = value;
                    this.RaisePropertyChanged("BuildNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Developer {
            get {
                return this.DeveloperField;
            }
            set {
                if ((object.ReferenceEquals(this.DeveloperField, value) != true)) {
                    this.DeveloperField = value;
                    this.RaisePropertyChanged("Developer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.BuildingDto.HousesType[] HousesTypeDto {
            get {
                return this.HousesTypeDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.HousesTypeDtoField, value) != true)) {
                    this.HousesTypeDtoField = value;
                    this.RaisePropertyChanged("HousesTypeDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="BuildingDto.HousesType", Namespace="http://schemas.datacontract.org/2004/07/JMS.DTO.Ptm")]
        [System.SerializableAttribute()]
        public partial class HousesType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long PropertyTypeIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PropertyTypeNameField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public long PropertyTypeID {
                get {
                    return this.PropertyTypeIDField;
                }
                set {
                    if ((this.PropertyTypeIDField.Equals(value) != true)) {
                        this.PropertyTypeIDField = value;
                        this.RaisePropertyChanged("PropertyTypeID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PropertyTypeName {
                get {
                    return this.PropertyTypeNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.PropertyTypeNameField, value) != true)) {
                        this.PropertyTypeNameField = value;
                        this.RaisePropertyChanged("PropertyTypeName");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectDto", Namespace="http://schemas.datacontract.org/2004/07/JMS.DTO.Ptm")]
    [System.SerializableAttribute()]
    public partial class ProjectDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BuildIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuildingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeveloperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HandOverDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.ProjectHistory[] ProjectHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectManagerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectManagerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.ProjectDto.PropertyTypeList[] PropertyTypeDtoListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildAddress {
            get {
                return this.BuildAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildAddressField, value) != true)) {
                    this.BuildAddressField = value;
                    this.RaisePropertyChanged("BuildAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BuildID {
            get {
                return this.BuildIDField;
            }
            set {
                if ((this.BuildIDField.Equals(value) != true)) {
                    this.BuildIDField = value;
                    this.RaisePropertyChanged("BuildID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildName {
            get {
                return this.BuildNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildNameField, value) != true)) {
                    this.BuildNameField = value;
                    this.RaisePropertyChanged("BuildName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildNo {
            get {
                return this.BuildNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildNoField, value) != true)) {
                    this.BuildNoField = value;
                    this.RaisePropertyChanged("BuildNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuildingStatus {
            get {
                return this.BuildingStatusField;
            }
            set {
                if ((this.BuildingStatusField.Equals(value) != true)) {
                    this.BuildingStatusField = value;
                    this.RaisePropertyChanged("BuildingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentNo {
            get {
                return this.DepartmentNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNoField, value) != true)) {
                    this.DepartmentNoField = value;
                    this.RaisePropertyChanged("DepartmentNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Developer {
            get {
                return this.DeveloperField;
            }
            set {
                if ((object.ReferenceEquals(this.DeveloperField, value) != true)) {
                    this.DeveloperField = value;
                    this.RaisePropertyChanged("Developer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HandOverDate {
            get {
                return this.HandOverDateField;
            }
            set {
                if ((this.HandOverDateField.Equals(value) != true)) {
                    this.HandOverDateField = value;
                    this.RaisePropertyChanged("HandOverDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectAddress {
            get {
                return this.ProjectAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectAddressField, value) != true)) {
                    this.ProjectAddressField = value;
                    this.RaisePropertyChanged("ProjectAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.ProjectHistory[] ProjectHistory {
            get {
                return this.ProjectHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectHistoryField, value) != true)) {
                    this.ProjectHistoryField = value;
                    this.RaisePropertyChanged("ProjectHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectManagerID {
            get {
                return this.ProjectManagerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectManagerIDField, value) != true)) {
                    this.ProjectManagerIDField = value;
                    this.RaisePropertyChanged("ProjectManagerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectManagerName {
            get {
                return this.ProjectManagerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectManagerNameField, value) != true)) {
                    this.ProjectManagerNameField = value;
                    this.RaisePropertyChanged("ProjectManagerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectNo {
            get {
                return this.ProjectNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNoField, value) != true)) {
                    this.ProjectNoField = value;
                    this.RaisePropertyChanged("ProjectNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.ProjectDto.PropertyTypeList[] PropertyTypeDtoList {
            get {
                return this.PropertyTypeDtoListField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyTypeDtoListField, value) != true)) {
                    this.PropertyTypeDtoListField = value;
                    this.RaisePropertyChanged("PropertyTypeDtoList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ProjectDto.PropertyTypeList", Namespace="http://schemas.datacontract.org/2004/07/JMS.DTO.Ptm")]
        [System.SerializableAttribute()]
        public partial class PropertyTypeList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long PropertyTypeIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PropertyTypeNameField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public long PropertyTypeID {
                get {
                    return this.PropertyTypeIDField;
                }
                set {
                    if ((this.PropertyTypeIDField.Equals(value) != true)) {
                        this.PropertyTypeIDField = value;
                        this.RaisePropertyChanged("PropertyTypeID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PropertyTypeName {
                get {
                    return this.PropertyTypeNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.PropertyTypeNameField, value) != true)) {
                        this.PropertyTypeNameField = value;
                        this.RaisePropertyChanged("PropertyTypeName");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectHistory", Namespace="http://schemas.datacontract.org/2004/07/JMS.DTO")]
    [System.SerializableAttribute()]
    public partial class ProjectHistory : ConsoleApplication1.ServiceReference1.BaseDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldProjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProjectSysNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldProjectName {
            get {
                return this.OldProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OldProjectNameField, value) != true)) {
                    this.OldProjectNameField = value;
                    this.RaisePropertyChanged("OldProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProjectSysNo {
            get {
                return this.ProjectSysNoField;
            }
            set {
                if ((this.ProjectSysNoField.Equals(value) != true)) {
                    this.ProjectSysNoField = value;
                    this.RaisePropertyChanged("ProjectSysNo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDto", Namespace="http://schemas.datacontract.org/2004/07/JMS.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.ProjectHistory))]
    public partial class BaseDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime _createDateField;
        
        private System.DateTime _modifyDateField;
        
        private int AllCountk__BackingFieldField;
        
        private string CreateUserNamek__BackingFieldField;
        
        private string CreateUserNok__BackingFieldField;
        
        private bool IsDeletek__BackingFieldField;
        
        private string ModifyUserNamek__BackingFieldField;
        
        private string ModifyUserNok__BackingFieldField;
        
        private string Secretk__BackingFieldField;
        
        private long SysNok__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate {
            get {
                return this._createDateField;
            }
            set {
                if ((this._createDateField.Equals(value) != true)) {
                    this._createDateField = value;
                    this.RaisePropertyChanged("_createDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _modifyDate {
            get {
                return this._modifyDateField;
            }
            set {
                if ((this._modifyDateField.Equals(value) != true)) {
                    this._modifyDateField = value;
                    this.RaisePropertyChanged("_modifyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AllCount>k__BackingField", IsRequired=true)]
        public int AllCountk__BackingField {
            get {
                return this.AllCountk__BackingFieldField;
            }
            set {
                if ((this.AllCountk__BackingFieldField.Equals(value) != true)) {
                    this.AllCountk__BackingFieldField = value;
                    this.RaisePropertyChanged("AllCountk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreateUserName>k__BackingField", IsRequired=true)]
        public string CreateUserNamek__BackingField {
            get {
                return this.CreateUserNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserNamek__BackingFieldField, value) != true)) {
                    this.CreateUserNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("CreateUserNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreateUserNo>k__BackingField", IsRequired=true)]
        public string CreateUserNok__BackingField {
            get {
                return this.CreateUserNok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserNok__BackingFieldField, value) != true)) {
                    this.CreateUserNok__BackingFieldField = value;
                    this.RaisePropertyChanged("CreateUserNok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsDelete>k__BackingField", IsRequired=true)]
        public bool IsDeletek__BackingField {
            get {
                return this.IsDeletek__BackingFieldField;
            }
            set {
                if ((this.IsDeletek__BackingFieldField.Equals(value) != true)) {
                    this.IsDeletek__BackingFieldField = value;
                    this.RaisePropertyChanged("IsDeletek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ModifyUserName>k__BackingField", IsRequired=true)]
        public string ModifyUserNamek__BackingField {
            get {
                return this.ModifyUserNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifyUserNamek__BackingFieldField, value) != true)) {
                    this.ModifyUserNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("ModifyUserNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ModifyUserNo>k__BackingField", IsRequired=true)]
        public string ModifyUserNok__BackingField {
            get {
                return this.ModifyUserNok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifyUserNok__BackingFieldField, value) != true)) {
                    this.ModifyUserNok__BackingFieldField = value;
                    this.RaisePropertyChanged("ModifyUserNok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Secret>k__BackingField", IsRequired=true)]
        public string Secretk__BackingField {
            get {
                return this.Secretk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Secretk__BackingFieldField, value) != true)) {
                    this.Secretk__BackingFieldField = value;
                    this.RaisePropertyChanged("Secretk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SysNo>k__BackingField", IsRequired=true)]
        public long SysNok__BackingField {
            get {
                return this.SysNok__BackingFieldField;
            }
            set {
                if ((this.SysNok__BackingFieldField.Equals(value) != true)) {
                    this.SysNok__BackingFieldField = value;
                    this.RaisePropertyChanged("SysNok__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomDto", Namespace="http://schemas.datacontract.org/2004/07/JMS.DTO.Ptm")]
    [System.SerializableAttribute()]
    public partial class RoomDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllRowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageAllCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.RoomDto.Room[] RoomListDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllRows {
            get {
                return this.AllRowsField;
            }
            set {
                if ((this.AllRowsField.Equals(value) != true)) {
                    this.AllRowsField = value;
                    this.RaisePropertyChanged("AllRows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPageIndex {
            get {
                return this.CurrentPageIndexField;
            }
            set {
                if ((this.CurrentPageIndexField.Equals(value) != true)) {
                    this.CurrentPageIndexField = value;
                    this.RaisePropertyChanged("CurrentPageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageAllCount {
            get {
                return this.PageAllCountField;
            }
            set {
                if ((this.PageAllCountField.Equals(value) != true)) {
                    this.PageAllCountField = value;
                    this.RaisePropertyChanged("PageAllCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.RoomDto.Room[] RoomListDto {
            get {
                return this.RoomListDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomListDtoField, value) != true)) {
                    this.RoomListDtoField = value;
                    this.RaisePropertyChanged("RoomListDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="RoomDto.Room", Namespace="http://schemas.datacontract.org/2004/07/JMS.DTO.Ptm")]
        [System.SerializableAttribute()]
        public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int FloorNoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string FullAddressField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int HallNumField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int OrientationField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ParentRoomIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ProjectNameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PropertyTypeNameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private decimal RoomAreaField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RoomIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RoomNameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RoomNoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int RoomNumField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string SeatNameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int ToiletNumField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long UinitIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string UinitNameField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int FloorNo {
                get {
                    return this.FloorNoField;
                }
                set {
                    if ((this.FloorNoField.Equals(value) != true)) {
                        this.FloorNoField = value;
                        this.RaisePropertyChanged("FloorNo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FullAddress {
                get {
                    return this.FullAddressField;
                }
                set {
                    if ((object.ReferenceEquals(this.FullAddressField, value) != true)) {
                        this.FullAddressField = value;
                        this.RaisePropertyChanged("FullAddress");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int HallNum {
                get {
                    return this.HallNumField;
                }
                set {
                    if ((this.HallNumField.Equals(value) != true)) {
                        this.HallNumField = value;
                        this.RaisePropertyChanged("HallNum");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int Orientation {
                get {
                    return this.OrientationField;
                }
                set {
                    if ((this.OrientationField.Equals(value) != true)) {
                        this.OrientationField = value;
                        this.RaisePropertyChanged("Orientation");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ParentRoomID {
                get {
                    return this.ParentRoomIDField;
                }
                set {
                    if ((object.ReferenceEquals(this.ParentRoomIDField, value) != true)) {
                        this.ParentRoomIDField = value;
                        this.RaisePropertyChanged("ParentRoomID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ProjectName {
                get {
                    return this.ProjectNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                        this.ProjectNameField = value;
                        this.RaisePropertyChanged("ProjectName");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PropertyTypeName {
                get {
                    return this.PropertyTypeNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.PropertyTypeNameField, value) != true)) {
                        this.PropertyTypeNameField = value;
                        this.RaisePropertyChanged("PropertyTypeName");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public decimal RoomArea {
                get {
                    return this.RoomAreaField;
                }
                set {
                    if ((this.RoomAreaField.Equals(value) != true)) {
                        this.RoomAreaField = value;
                        this.RaisePropertyChanged("RoomArea");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string RoomID {
                get {
                    return this.RoomIDField;
                }
                set {
                    if ((object.ReferenceEquals(this.RoomIDField, value) != true)) {
                        this.RoomIDField = value;
                        this.RaisePropertyChanged("RoomID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string RoomName {
                get {
                    return this.RoomNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.RoomNameField, value) != true)) {
                        this.RoomNameField = value;
                        this.RaisePropertyChanged("RoomName");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string RoomNo {
                get {
                    return this.RoomNoField;
                }
                set {
                    if ((object.ReferenceEquals(this.RoomNoField, value) != true)) {
                        this.RoomNoField = value;
                        this.RaisePropertyChanged("RoomNo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int RoomNum {
                get {
                    return this.RoomNumField;
                }
                set {
                    if ((this.RoomNumField.Equals(value) != true)) {
                        this.RoomNumField = value;
                        this.RaisePropertyChanged("RoomNum");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string SeatName {
                get {
                    return this.SeatNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.SeatNameField, value) != true)) {
                        this.SeatNameField = value;
                        this.RaisePropertyChanged("SeatName");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int ToiletNum {
                get {
                    return this.ToiletNumField;
                }
                set {
                    if ((this.ToiletNumField.Equals(value) != true)) {
                        this.ToiletNumField = value;
                        this.RaisePropertyChanged("ToiletNum");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public long UinitID {
                get {
                    return this.UinitIDField;
                }
                set {
                    if ((this.UinitIDField.Equals(value) != true)) {
                        this.UinitIDField = value;
                        this.RaisePropertyChanged("UinitID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string UinitName {
                get {
                    return this.UinitNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.UinitNameField, value) != true)) {
                        this.UinitNameField = value;
                        this.RaisePropertyChanged("UinitName");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseDto", Namespace="http://schemas.datacontract.org/2004/07/JMS.DTO.Ptm")]
    [System.SerializableAttribute()]
    public partial class CaseDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OperationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalMoneyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseID {
            get {
                return this.CaseIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseIDField, value) != true)) {
                    this.CaseIDField = value;
                    this.RaisePropertyChanged("CaseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellPhone {
            get {
                return this.CellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellPhoneField, value) != true)) {
                    this.CellPhoneField = value;
                    this.RaisePropertyChanged("CellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OperationDate {
            get {
                return this.OperationDateField;
            }
            set {
                if ((this.OperationDateField.Equals(value) != true)) {
                    this.OperationDateField = value;
                    this.RaisePropertyChanged("OperationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalArea {
            get {
                return this.TotalAreaField;
            }
            set {
                if ((this.TotalAreaField.Equals(value) != true)) {
                    this.TotalAreaField = value;
                    this.RaisePropertyChanged("TotalArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalMoney {
            get {
                return this.TotalMoneyField;
            }
            set {
                if ((this.TotalMoneyField.Equals(value) != true)) {
                    this.TotalMoneyField = value;
                    this.RaisePropertyChanged("TotalMoney");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HouseSeatDto", Namespace="http://schemas.datacontract.org/2004/07/JMS.DTO.Ptm")]
    [System.SerializableAttribute()]
    public partial class HouseSeatDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HouseSeatIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseSeatNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ParentHouseSeatIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HouseSeatID {
            get {
                return this.HouseSeatIDField;
            }
            set {
                if ((this.HouseSeatIDField.Equals(value) != true)) {
                    this.HouseSeatIDField = value;
                    this.RaisePropertyChanged("HouseSeatID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseSeatName {
            get {
                return this.HouseSeatNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseSeatNameField, value) != true)) {
                    this.HouseSeatNameField = value;
                    this.RaisePropertyChanged("HouseSeatName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParentHouseSeatID {
            get {
                return this.ParentHouseSeatIDField;
            }
            set {
                if ((this.ParentHouseSeatIDField.Equals(value) != true)) {
                    this.ParentHouseSeatIDField = value;
                    this.RaisePropertyChanged("ParentHouseSeatID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectMemberDto", Namespace="http://schemas.datacontract.org/2004/07/JMS.DTO.Ptm")]
    [System.SerializableAttribute()]
    public partial class ProjectMemberDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DomainAccount {
            get {
                return this.DomainAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainAccountField, value) != true)) {
                    this.DomainAccountField = value;
                    this.RaisePropertyChanged("DomainAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpName {
            get {
                return this.EmpNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpNameField, value) != true)) {
                    this.EmpNameField = value;
                    this.RaisePropertyChanged("EmpName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpNo {
            get {
                return this.EmpNoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpNoField, value) != true)) {
                    this.EmpNoField = value;
                    this.RaisePropertyChanged("EmpNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupervisorName {
            get {
                return this.SupervisorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorNameField, value) != true)) {
                    this.SupervisorNameField = value;
                    this.RaisePropertyChanged("SupervisorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupervisorNo {
            get {
                return this.SupervisorNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorNoField, value) != true)) {
                    this.SupervisorNoField = value;
                    this.RaisePropertyChanged("SupervisorNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IInterfaceForPTMService")]
    public interface IInterfaceForPTMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetBuilding", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetBuildingResponse")]
        ConsoleApplication1.ServiceReference1.BuildingDto[] GetBuilding(string buildAddress, string buildNo, string buildName, long[] buildID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetBuilding", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetBuildingResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.BuildingDto[]> GetBuildingAsync(string buildAddress, string buildNo, string buildName, long[] buildID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetProject", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetProjectResponse")]
        ConsoleApplication1.ServiceReference1.ProjectDto[] GetProject(string projectAddress, string projectNo, string projectName, long[] projectID, long buildID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetProject", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetProjectResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ProjectDto[]> GetProjectAsync(string projectAddress, string projectNo, string projectName, long[] projectID, long buildID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetAllProjects", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetAllProjectsResponse")]
        ConsoleApplication1.ServiceReference1.ProjectDto[] GetAllProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetAllProjects", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetAllProjectsResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ProjectDto[]> GetAllProjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetRoom", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetRoomResponse")]
        ConsoleApplication1.ServiceReference1.RoomDto GetRoom(long[] houseSeatID, long projectID, long[] unitID, string roomID, string roomNo, string unitName, string houseSeatName, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetRoom", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetRoomResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.RoomDto> GetRoomAsync(long[] houseSeatID, long projectID, long[] unitID, string roomID, string roomNo, string unitName, string houseSeatName, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetCase", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetCaseResponse")]
        ConsoleApplication1.ServiceReference1.CaseDto[] GetCase(string[] roomID, int[] salesType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetCase", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetCaseResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CaseDto[]> GetCaseAsync(string[] roomID, int[] salesType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetHouseSeat", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetHouseSeatResponse")]
        ConsoleApplication1.ServiceReference1.HouseSeatDto[] GetHouseSeat(System.Nullable<long> projectID, long[] houseSeatID, string projectName, string houseSeatName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetHouseSeat", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetHouseSeatResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.HouseSeatDto[]> GetHouseSeatAsync(System.Nullable<long> projectID, long[] houseSeatID, string projectName, string houseSeatName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetProjectMember", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetProjectMemberResponse")]
        ConsoleApplication1.ServiceReference1.ProjectMemberDto[] GetProjectMember(long projectID, int[] role, string empNo, string empName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetProjectMember", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetProjectMemberResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ProjectMemberDto[]> GetProjectMemberAsync(long projectID, int[] role, string empNo, string empName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetSingleRoom", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetSingleRoomResponse")]
        ConsoleApplication1.ServiceReference1.RoomDto.Room GetSingleRoom(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceForPTMService/GetSingleRoom", ReplyAction="http://tempuri.org/IInterfaceForPTMService/GetSingleRoomResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.RoomDto.Room> GetSingleRoomAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterfaceForPTMServiceChannel : ConsoleApplication1.ServiceReference1.IInterfaceForPTMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceForPTMServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IInterfaceForPTMService>, ConsoleApplication1.ServiceReference1.IInterfaceForPTMService {
        
        public InterfaceForPTMServiceClient() {
        }
        
        public InterfaceForPTMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceForPTMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceForPTMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceForPTMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1.ServiceReference1.BuildingDto[] GetBuilding(string buildAddress, string buildNo, string buildName, long[] buildID) {
            return base.Channel.GetBuilding(buildAddress, buildNo, buildName, buildID);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.BuildingDto[]> GetBuildingAsync(string buildAddress, string buildNo, string buildName, long[] buildID) {
            return base.Channel.GetBuildingAsync(buildAddress, buildNo, buildName, buildID);
        }
        
        public ConsoleApplication1.ServiceReference1.ProjectDto[] GetProject(string projectAddress, string projectNo, string projectName, long[] projectID, long buildID) {
            return base.Channel.GetProject(projectAddress, projectNo, projectName, projectID, buildID);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ProjectDto[]> GetProjectAsync(string projectAddress, string projectNo, string projectName, long[] projectID, long buildID) {
            return base.Channel.GetProjectAsync(projectAddress, projectNo, projectName, projectID, buildID);
        }
        
        public ConsoleApplication1.ServiceReference1.ProjectDto[] GetAllProjects() {
            return base.Channel.GetAllProjects();
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ProjectDto[]> GetAllProjectsAsync() {
            return base.Channel.GetAllProjectsAsync();
        }
        
        public ConsoleApplication1.ServiceReference1.RoomDto GetRoom(long[] houseSeatID, long projectID, long[] unitID, string roomID, string roomNo, string unitName, string houseSeatName, int pageIndex, int pageSize) {
            return base.Channel.GetRoom(houseSeatID, projectID, unitID, roomID, roomNo, unitName, houseSeatName, pageIndex, pageSize);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.RoomDto> GetRoomAsync(long[] houseSeatID, long projectID, long[] unitID, string roomID, string roomNo, string unitName, string houseSeatName, int pageIndex, int pageSize) {
            return base.Channel.GetRoomAsync(houseSeatID, projectID, unitID, roomID, roomNo, unitName, houseSeatName, pageIndex, pageSize);
        }
        
        public ConsoleApplication1.ServiceReference1.CaseDto[] GetCase(string[] roomID, int[] salesType) {
            return base.Channel.GetCase(roomID, salesType);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CaseDto[]> GetCaseAsync(string[] roomID, int[] salesType) {
            return base.Channel.GetCaseAsync(roomID, salesType);
        }
        
        public ConsoleApplication1.ServiceReference1.HouseSeatDto[] GetHouseSeat(System.Nullable<long> projectID, long[] houseSeatID, string projectName, string houseSeatName) {
            return base.Channel.GetHouseSeat(projectID, houseSeatID, projectName, houseSeatName);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.HouseSeatDto[]> GetHouseSeatAsync(System.Nullable<long> projectID, long[] houseSeatID, string projectName, string houseSeatName) {
            return base.Channel.GetHouseSeatAsync(projectID, houseSeatID, projectName, houseSeatName);
        }
        
        public ConsoleApplication1.ServiceReference1.ProjectMemberDto[] GetProjectMember(long projectID, int[] role, string empNo, string empName) {
            return base.Channel.GetProjectMember(projectID, role, empNo, empName);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ProjectMemberDto[]> GetProjectMemberAsync(long projectID, int[] role, string empNo, string empName) {
            return base.Channel.GetProjectMemberAsync(projectID, role, empNo, empName);
        }
        
        public ConsoleApplication1.ServiceReference1.RoomDto.Room GetSingleRoom(string id) {
            return base.Channel.GetSingleRoom(id);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.RoomDto.Room> GetSingleRoomAsync(string id) {
            return base.Channel.GetSingleRoomAsync(id);
        }
    }
}
